export const Meals = {
    BREAKFAST: "Breakfast",
    LUNCH: "Lunch",
    DINNER: "Dinner",
    SNACK: "Snack"
}

export const Dishes = {
    PANCAKES: {
      name: "Pancakes",
      calories: 350,
      carbs: 60,
      protein: 8,
      fat: 10,
    },
    OATMEAL: {
      name: "Oatmeal",
      calories: 220,
      carbs: 45,
      protein: 6,
      fat: 4,
    },
    SANDWICH: {
      name: "Sandwich",
      calories: 300,
      carbs: 30,
      protein: 15,
      fat: 14,
    },
    YOGURTH: {
      name: "Yogurth",
      calories: 250,
      carbs: 20,
      protein: 12,
      fat: 15,
    },
    SMOOTHIE: {
      name: "Smoothie",
      calories: 180,
      carbs: 40,
      protein: 5,
      fat: 2,
    },
    CHICKENRICE: {
      name: "ChickenRice",
      calories: 400,
      carbs: 45,
      protein: 30,
      fat: 12,
    },
    TUNASALAD: {
      name: "TunaSalad",
      calories: 320,
      carbs: 25,
      protein: 20,
      fat: 14,
    },
    VEGETABLECURRY: {
      name: "VegetableCurry",
      calories: 300,
      carbs: 50,
      protein: 10,
      fat: 8,
    },
    PASTAVEGETABLES: {
      name: "PastaVegetables",
      calories: 350,
      carbs: 55,
      protein: 12,
      fat: 10,
    },
    GRILLEDCHICKENSALAD: {
      name: "GrilledChickenSalad",
      calories: 280,
      carbs: 15,
      protein: 25,
      fat: 16,
    },
    SALMONPOTATOES: {
      name: "SalmonPotatoes",
      calories: 450,
      carbs: 30,
      protein: 35,
      fat: 20,
    },
    TOFUVEGETABLES: {
      name: "TofuVegetables",
      calories: 320,
      carbs: 40,
      protein: 18,
      fat: 14,
    },
    CHICKENVEGETABLES: {
      name: "ChickenVegetables",
      calories: 380,
      carbs: 40,
      protein: 22,
      fat: 15,
    },
    GRILLEDFISH: {
      name: "GrilledFish",
      calories: 300,
      carbs: 25,
      protein: 28,
      fat: 12,
    },
    PASTAPESTO: {
      name: "PastaPesto",
      calories: 400,
      carbs: 45,
      protein: 10,
      fat: 18,
    },
    FRUITSALAD: {
      name: "FruitSalad",
      calories: 150,
      carbs: 35,
      protein: 2,
      fat: 1,
    },
    YOGURTHALMONDS: {
      name: "YogurthAlmonds",
      calories: 280,
      carbs: 18,
      protein: 15,
      fat: 18,
    },
    HUMMUSVEGETABLES: {
      name: "HummusVegetables",
      calories: 200,
      carbs: 25,
      protein: 8,
      fat: 10,
    },
    NUTSFRUITS: {
      name: "NutsFruits",
      calories: 220,
      carbs: 30,
      protein: 5,
      fat: 12,
    },
    CRACKERSCHEESE: {
      name: "CrackersCheese",
      calories: 180,
      carbs: 20,
      protein: 8,
      fat: 10,
    },
  };
  